[tool.bumpversion]
current_version = "1.7.4"
commit = true
tag = true

[[tool.bumpversion.files]]
filename = "setup.py"
search = "version=\"{current_version}\""
replace = "version=\"{new_version}\""

[[tool.bumpversion.files]]
filename = "dtw/__init__.py"
search = "__version__ = '{current_version}'"
replace = "__version__ = '{new_version}'"
